### PR TITLE
Fix coloring of brackets and variables

### LINKED ISSUE #27: JavaScript variables and brackets are colored incorrectly
Here's what a block of JavaScript looks like with atom-material-syntax (dark):

screen shot 2016-01-31 at 02 11 05

And here's what the same code looks like with One Dark syntax:

screen shot 2016-01-31 at 02 11 21

The problems begin at the first line. The left parenthesis, comma, and bracket are all highlighted in the 'function' color when they should be plain instead. This carries over to line 2 where both the variable name and the semicolon are highlighted. Strangely enough, the 'element' variable is highlighted correctly later on in the same file.

I'm pretty sure it's been this way ever since I first installed it a month or so ago, so it most likely isn't a recent regression. Let me know if you need any more info. Thanks!

### PR DESCRIPTION
**Pull request by D1SC0tech**
Fixes #27
A bunch of non-functions were being colored like functions

### CODE REVIEW

**Comment by silvestreh** [comment]
Got a screenshot?

**Comment by silvestreh** [comment]
Also… is it related to #27?

**Comment by silvestreh** [comment]
Nevermind… :D

**Comment by D1SC0tech** [comment]
This got regressed after the recent sync with Sublime, can you delete that line again? I'd be happy to create a new PR if you'd like. Same goes for material-design-dark and material-design-light.

**Comment by silvestreh** [comment]
Please do include screenshots and whatnot to better describe the unwanted behavior, because this PR disabled method highlighting for some languages. Check #30 for more info.

**Comment by D1SC0tech** [comment]
Screenshots are in #27, it's the same issue.

**Pull request merged**
